" Vi sucks
set nocompatible

" Encoding
set encoding=utf-8
set fileencoding=utf-8

" GUI-dependant options
if has("gui_running")
    " GUI TrueType font
    if has("win32") || has("win16")
        set guifont=Liberation_Mono:h10:cANSI
    else
        set guifont=Inconsolata\ Medium\ 11
    endif
    " Remove useless buttons and menu bar
    set guioptions-=m
    set guioptions-=T
    " Set default window size
    set lines=30 columns=85
else
    " Use lines only in terminal
    set cursorline cursorcolumn
    set background=dark
endif

" Syntax options
syn on

" Indent options
set showmatch
set shiftwidth=4 softtabstop=4 expandtab " Use spaces instead of tabs
set tabstop=4 " Size of a tab character
set smartindent

" Mouse is evil, but sometimes useful
set mouse=a

" Interface
set number

set showcmd
set colorcolumn=80
set ruler
set scrolloff=3
set ls=2

" Allow files to be hidden in order to call :e without having to save
set hidden

" No audible bell but visual bell instead
set visualbell
set noerrorbells

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Faster scroll
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Changing leader key for a more azerty-friendly one (or not)
let mapleader = ','

" Do the same but with another key for the local leader key
let maplocalleader = ';'

" Leader bindings
" nmap <silent> <Leader>nu :set relativenumber<CR>
nnoremap <silent> <Leader>sp :set spell!<CR>
nnoremap <silent> <Leader>b :b#<CR>

" Autocmd stuff
if has("autocmd")

    " Delete all useless whitespaces at the end of each line on saving
    au BufWritePre * :%s/\s+$//e

    " Remember location in file
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif

    " Highlight trailing spaces
    au BufWinEnter * hi ExtraWhitespace ctermbg=red guibg=red
    au BufWinEnter * match ExtraWhitespace /\s\+$/

    " Custom syntax highlighting for specific extensions
    au BufNewFile,BufRead *.json set ft=javascript
    au BufNewFile,BufRead *.eliom set ft=ocaml

    " Yaml folding configuration
    au BufRead,BufNewFile *.{yml,yaml} set ft=yaml

    " Consider Markdown files as text files
    au BufRead,BufNewFile *.md set ft=markdown

    " Autowrap on editing mails
    au BufRead /tmp/mutt-* set tw=79
endif

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Wordwrap
set wrap
set linebreak

" Showing invisible characters with cool unicode chars
exec "set listchars=tab:\uBB ,trail:\uB7,nbsp:\u237D"
set list

hi NonText ctermfg=8 guifg=grey
hi SpecialKey ctermfg=8 guifg=grey

" Spellchecking
set spelllang=~/.vim/spell/fr.utf-8.spl
set spellfile=~/.vim/spell/fr.utf-8.add

" Completion
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" Color scheme for GUI only
if has('gui_running')
    colorscheme pygments
endif

" If the bundles were installed, load their configuration
if isdirectory('/home/microjoe/.vim/bundle/') == 1
    execute pathogen#infect()
    source ~/.vim/bundles.vim
endif
