set nocompatible
source ~/.vim/bundles.vim

" Encoding
set encoding=utf-8
set fileencoding=utf-8

" GUI options
if has("gui_running")
    " GUI TrueType font
    set guifont=Liberation_Mono:h10:cANSI
    " Remove useless buttons and menu bar
    set guioptions-=m
    set guioptions-=T
    " Set default window size
    set lines=30 columns=85
endif

" Syntax options
syn on
set background=dark

" Indent options
set showmatch
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent

" Line numbers
set number

" Interface
set mouse=a
set cursorline
set showcmd
set colorcolumn=80
set ruler
set ls=2

" Changing leader key for a more azerty-friendly one
let mapleader = ','
nmap <silent> <Leader>nu :set relativenumber<CR>

" Theme
let g:hybrid_use_Xresources = 1
colorscheme hybrid
set background=dark

" Delete all whitespace in end of line
autocmd BufWritePre * :%s/\s+$//e

" Doxygen
let g:DoxygenToolkit_commentType = "C++"

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Remember location in file
if has("autocmd")
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript

" Yaml folding configuration
au BufRead,BufNewFile *.{yml,yaml} set foldmethod=indent

" Wordwrap
set wrap
set linebreak

" Showing invisible characters
set listchars=tab:>-,trail:-


" Spellchecking
set spelllang=~/.vim/spell/fr.utf-8.spl
set spellfile=~/.vim/spell/fr.utf-8.add

function SetTextSettings()
    set tw=79
endfunction

autocmd BufNewFile,BufRead *.txt call SetTextSettings()
autocmd BufNewFile,BufRead *.md  call SetTextSettings()
autocmd BufNewFile,BufRead *.tex call SetTextSettings()

" Completion
filetype plugin on
set omnifunc=syntaxcomplete#Complete
