set nocompatible
source ~/.vim/bundles.vim

" Encoding
set encoding=utf-8
set fileencoding=utf-8

" GUI options
if has("gui_running")
    " GUI TrueType font
    set guifont=Liberation_Mono:h10:cANSI
    " Remove useless buttons and menu bar
    set guioptions-=m
    set guioptions-=T
    " Set default window size
    set lines=30 columns=85
endif

" Syntax options
syn on
set background=dark

" Indent options
set showmatch
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent

" Mouse is evil, but sometimes useful
set mouse=a

" Interface
set number
set relativenumber
set cursorline cursorcolumn
set showcmd
set colorcolumn=80
set ruler
set scrolloff=3
set ls=2

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Faster scrolldown
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Changing leader key for a more azerty-friendly one
let mapleader = ','

" Leader bindings
" nmap <silent> <Leader>nu :set relativenumber<CR>

" Delete all useless whitespaces at the end of each line on saving
autocmd BufWritePre * :%s/\s+$//e

" Remember location in file
if has("autocmd")
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Custom syntax highlighting for specific extensions
au BufNewFile,BufRead *.json set ft=javascript
au BufNewFile,BufRead *.eliom set ft=ocaml

" Yaml folding configuration
au BufRead,BufNewFile *.{yml,yaml} set foldmethod=indent

" Wordwrap
set wrap
set linebreak

" Showing invisible characters with cool unicode chars
exec "set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:\u237D"
set list

" Spellchecking
set spelllang=~/.vim/spell/fr.utf-8.spl
set spellfile=~/.vim/spell/fr.utf-8.add

" Automatic wrap for certain kind of files (human text ones)
function SetTextSettings()
    set tw=79
endfunction

autocmd BufNewFile,BufRead *.txt call SetTextSettings()
autocmd BufNewFile,BufRead *.md  call SetTextSettings()
autocmd BufNewFile,BufRead *.tex call SetTextSettings()

" Completion
filetype plugin on
set omnifunc=syntaxcomplete#Complete
